admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /Admin
blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog

opportunityIndex:
    resource: "@OpportunityBundle/Resources/config/routing.yml"
    prefix:   /opportunity
app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
contract:
    resource: "@ContractBundle/Resources/config/routing.yml"
    prefix:   /contract
mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix:   /notifications
